### ISSUE TITLE
set step?

### ISSUE THREAD

**Issue by louman** [sabhiram/angular-slick-slider#1]
Hi, is it possible to set the step?

**Comment by sabhiram** [comment]
There are not yet any increment / decrement options for the slider. You mean to say, if step is 2 and the range is [0, 10] only [0,2,4,6,8,10] would be valid values?

**Comment by louman** [comment]
Yes...

I have sent you a pull request :)

**Comment by sabhiram** [comment]
oh awesome - ill take a quick look ty

**Comment by sabhiram** [comment]
closed by #2 - ty muchly!

Btw - how did you stumble across this module if you don't mind me asking?

**Comment by louman** [comment]
Man... your slider saved my life. 

I have an app that runs only on Samsung's Galaxy tab 4 and your slider was the only one that worked flawlessly :)

**Comment by sabhiram** [comment]
Oh thats awesome to hear man! Appreciate the PR and the kind words :)
