### ISSUE TITLE
Border 

### ISSUE THREAD

**Issue by Stan92** [sabhiram/angular-slick-slider#3]
Hi,
I try to figure out how to remove the blue border that appears while you start sliding the thumb.
I have no clue how to do?
Any help?

**Comment by sabhiram** [comment]
Oh wow, it has been a long while since I looked at this code :)

@Stan92 - I think you can disable the "outline" css property on any input. You probably want to only do so when the input is "focused". To do so with CSS (assuming my class nomenclature), it would look something like this:

```
// CSS file
input.sab-slider-input:focus {
    outline: none;
}
```

**Comment by Stan92** [comment]
Thanks ;-) it works...

**Comment by sabhiram** [comment]
Awesome, glad that it worked for you :)
